services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\DoctrineSchema\API\SchemaExporter: '@EzSystems\DoctrineSchema\Exporter\SchemaExporter'
