services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\DoctrineSchema\API\SchemaExporter: '@EzSystems\DoctrineSchema\Exporter\SchemaExporter'

    EzSystems\DoctrineSchema\API\SchemaImporter: '@EzSystems\DoctrineSchema\Importer\SchemaImporter'

    EzSystems\DoctrineSchema\API\DbPlatformFactory: '@EzSystems\DoctrineSchema\Database\DbPlatformFactory'

    EzSystems\DoctrineSchema\API\Builder\SchemaBuilder: '@EzSystems\DoctrineSchema\Builder\SchemaBuilder'
