parameters:
    ez_doctrine_schema.default_table_options: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    _instanceof:
        EzSystems\DoctrineSchema\Database\DbPlatform\DbPlatform:
            tags: ['doctrine.dbplatform']

    EzSystems\DoctrineSchema\Exporter\:
        resource: '../../../lib/Exporter/*'

    EzSystems\DoctrineSchema\Importer\:
        resource: '../../../lib/Importer/*'

    EzSystems\DoctrineSchema\Database\DbPlatformFactory:
        arguments:
            $dbPlatforms: !tagged doctrine.dbplatform

    EzSystems\DoctrineSchema\Database\DbPlatform\:
        resource: '../../../lib/Database/DbPlatform/*'

    EzSystems\DoctrineSchema\Builder\SchemaBuilder:
        arguments:
            $defaultTableOptions: '%ez_doctrine_schema.default_table_options%'

    Doctrine\Common\EventManager: ~
