services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\DoctrineSchema\Exporter\:
        resource: '../../../lib/Exporter/*'

    EzSystems\DoctrineSchema\Database\DbPlatform\:
        resource: '../../../lib/Database/DbPlatform/*'

    EzSystems\DoctrineSchema\Importer\:
        resource: '../../../lib/Importer/*'
